```
#/etc/vimrc for global
start
:set number
":set relativenumber
:set autoindent
:set tabstop=4
:set shiftwidth=4
:set smarttab
:set softtabstop=4
:set mouse=a

" copy and paste
vnoremap <C-c> "+y
map <C-v> "+P
```
